Repository KNU-Finnect/finnect_backend, pull requests merged in 2024-06, with the labels that each got.

#100 feat: UserController에만 직접 로그 추가
  src/main/java/com/finnect/config/WebMvcConfig.java
  src/main/java/com/finnect/config/interceptor/LogInterceptor.java
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
Labels: Hotfix

#102 fix: username 제약 조건 삭제
  src/main/java/com/finnect/user/application/port/in/command/SignupCommand.java
  src/test/java/com/finnect/user/application/jwt/JwtProviderTests.java
  src/test/java/com/finnect/user/application/port/in/command/SignupCommandTests.java
Labels: 🐞 BugFix

#103 fix: 비밀번호에 '!', '*' 허용
  src/main/java/com/finnect/user/application/password/PasswordGenerator.java
  src/main/java/com/finnect/user/application/port/in/command/ChangePasswordCommand.java
  src/main/java/com/finnect/user/application/port/in/command/SignupCommand.java
  src/test/java/com/finnect/user/application/password/PasswordGeneratorTests.java
Labels: 🐞 BugFix

#110 Feat/109 move workspace api
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/in/web/request/ReissueWorkspaceRequest.java
  src/main/java/com/finnect/user/adapter/out/cache/entity/RefreshTokenEntity.java
  src/main/java/com/finnect/user/application/port/in/ReissueUseCase.java
  src/main/java/com/finnect/user/application/port/in/UserDetailsQuery.java
  src/main/java/com/finnect/user/application/port/in/command/ReissueWorkspaceCommand.java
  src/main/java/com/finnect/user/application/service/TokenService.java
  src/main/java/com/finnect/user/application/service/UserDetailsServiceImpl.java
  src/main/java/com/finnect/user/domain/RefreshToken.java
  src/main/java/com/finnect/user/domain/UserDetailsImpl.java
  src/main/java/com/finnect/user/state/RefreshTokenState.java
  src/main/java/com/finnect/user/vo/WorkspaceAuthority.java
Labels: ✨ Feature, 📬 API

#107 Feat/27 check default workspace
  src/main/java/com/finnect/user/application/port/in/CheckDefaultWorkspaceUseCase.java
  src/main/java/com/finnect/user/application/port/in/CheckDefaultWorkspaceUsecase.java
  src/main/java/com/finnect/user/application/port/in/MockService.java
  src/main/java/com/finnect/user/application/service/UserInfoService.java
  src/main/java/com/finnect/user/domain/User.java
  src/main/java/com/finnect/workspace/application/CreateWorkspaceService.java
  src/test/java/com/finnect/workspace/application/CreateWorkspaceServiceTest.java
Labels: ✨ Feature

#108 Feat/28 change default workspace
  src/main/java/com/finnect/user/application/port/in/ChangeDefaultWorkspaceUseCase.java
  src/main/java/com/finnect/user/application/port/in/MockService.java
  src/main/java/com/finnect/user/application/port/in/SetDefaultUsecase.java
  src/main/java/com/finnect/user/application/service/UserInfoService.java
  src/main/java/com/finnect/user/domain/User.java
  src/main/java/com/finnect/workspace/application/CreateWorkspaceService.java
  src/test/java/com/finnect/workspace/application/CreateWorkspaceServiceTest.java
Labels: ✨ Feature

#113 fix: JWT에서 워크스페이스 추출 누락 픽스
  src/main/java/com/finnect/user/application/jwt/JwtProvider.java
Labels: 🐞 BugFix, Hotfix

#118 Feat/111 user api exception handling
  src/main/java/com/finnect/common/ApiUtils.java
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/in/web/UserExceptionHandler.java
  src/main/java/com/finnect/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/finnect/user/adapter/out/persistence/entity/UserRepository.java
  src/main/java/com/finnect/user/application/port/in/VerifyEmailCodeUseCase.java
  src/main/java/com/finnect/user/application/port/in/exception/UserDuplicateException.java
  src/main/java/com/finnect/user/application/port/out/ExistsUserPort.java
  src/main/java/com/finnect/user/application/service/FindUsernameService.java
  src/main/java/com/finnect/user/application/service/ResetPasswordService.java
  src/main/java/com/finnect/user/application/service/SignupService.java
Labels: ✨ Feature, 📬 API

#116 Feat/115 implements token
  src/main/java/com/finnect/crm/adapter/in/web/controller/column/ColumnController.java
  src/main/java/com/finnect/crm/adapter/in/web/controller/deal/DealController.java
  src/main/java/com/finnect/crm/adapter/in/web/controller/dealLog/DealLogController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/column/CreateDealColumnRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/req/deal/CreateDealRequest.java
  src/main/java/com/finnect/crm/adapter/out/persistence/deal/DealEntity.java
Labels: 🥰 Accessibility

#119 Hotfix/117 signin api response
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationFilter.java
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
Labels: 📬 API, Hotfix

#123 fix: 인증 Context 초기화 누락 픽스
  src/main/java/com/finnect/user/adapter/in/security/AuthorizationFilter.java
Labels: 🐞 BugFix, Hotfix

#122 Feat/120 modify cell api
  src/main/java/com/finnect/crm/adapter/in/web/controller/cell/DealCellController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/cell/ModifyCellRequest.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/CellPersistenceLoadAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/CellPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/application/port/in/cell/ModifyDataCellUseCase.java
  src/main/java/com/finnect/crm/application/port/in/cell/ResetDataCellUseCase.java
  src/main/java/com/finnect/crm/application/port/out/cell/LoadDataCellPort.java
  src/main/java/com/finnect/crm/application/port/out/cell/SaveCellPort.java
  src/main/java/com/finnect/crm/application/service/cell/ModifyDataCellService.java
  src/main/java/com/finnect/crm/application/service/column/ModifyColumnService.java
Labels: 📬 API

#124 Feat/54 jwt
  src/main/java/com/finnect/crm/adapter/in/web/controller/company/CompanyController.java
  src/main/java/com/finnect/workspace/adaptor/in/web/MemberController.java
  src/main/java/com/finnect/workspace/adaptor/in/web/WorkspaceController.java
  src/main/java/com/finnect/workspace/application/CreateWorkspaceService.java
Labels: 🔨 Refactor

#128 Feat/127 exception handler
  src/main/java/com/finnect/common/error/CustomExceptionHandler.java
  src/main/java/com/finnect/common/error/NotFoundException.java
  src/main/java/com/finnect/crm/application/service/person/DeletePersonService.java
  src/main/java/com/finnect/workspace/adaptor/out/persistence/MemberPersistenceAdapter.java
  src/main/java/com/finnect/workspace/adaptor/out/persistence/WorkspacePersistenceAdapter.java
Labels: 📬 API

#129 Hotfix/121 unauth access
  src/main/java/com/finnect/user/adapter/in/security/AuthorizationFilter.java
  src/main/java/com/finnect/user/config/SecurityConfig.java
Labels: 🐞 BugFix, Hotfix

#135 fix: command에서 workspace id 삭제 및 workspace 생성시 인자 변경
  src/main/java/com/finnect/workspace/application/CreateWorkspaceService.java
  src/main/java/com/finnect/workspace/application/port/in/CreateWorkspaceCommand.java
Labels: 🐞 BugFix

#142 Hotfix/140 reissue
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationFilter.java
  src/main/java/com/finnect/user/config/SecurityConfig.java
Labels: 🐞 BugFix, 📬 API, Hotfix

#143 Hotfix/140 reissue
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationFilter.java
Labels: 🐞 BugFix, 📬 API, Hotfix

#148 Feat/147 get people
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonPersistenceAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonRepository.java
  src/main/java/com/finnect/crm/application/port/in/person/FindPeopleUsecase.java
  src/main/java/com/finnect/crm/application/port/out/person/LoadPeoplePort.java
  src/main/java/com/finnect/crm/application/service/person/FindPersonService.java
Labels: ✨ Feature, 📬 API

#146 Refactor/145 apply token
  src/main/java/com/finnect/crm/adapter/in/web/controller/company/CompanyController.java
  src/main/java/com/finnect/crm/adapter/in/web/res/company/LoadCompaniesResponse.java
Labels: 🐞 BugFix, 📬 API

#149 Feat/137 check member
  src/main/java/com/finnect/workspace/adaptor/in/web/MemberController.java
  src/main/java/com/finnect/workspace/adaptor/out/persistence/MemberPersistenceAdapter.java
  src/main/java/com/finnect/workspace/application/CheckAuthorityService.java
  src/main/java/com/finnect/workspace/application/FindMembersService.java
  src/main/java/com/finnect/workspace/application/port/in/CheckAuthorityUsecase.java
  src/main/java/com/finnect/workspace/application/port/in/FindMembersUsecase.java
  src/main/java/com/finnect/workspace/application/port/out/SearchMemberPort.java
Labels: ✨ Feature

#151 Feat/150 signout api
  src/main/java/com/finnect/common/error/CustomExceptionHandler.java
  src/main/java/com/finnect/common/error/DuplicateException.java
  src/main/java/com/finnect/common/error/NotVerifiedException.java
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/in/web/UserExceptionHandler.java
  src/main/java/com/finnect/user/adapter/out/cache/EmailCodeCacheAdapter.java
  src/main/java/com/finnect/user/adapter/out/cache/RefreshTokenCacheAdapter.java
  src/main/java/com/finnect/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/finnect/user/application/port/in/FindUsernameUseCase.java
  src/main/java/com/finnect/user/application/port/in/ResetPasswordUseCase.java
  src/main/java/com/finnect/user/application/port/in/SignoutUseCase.java
  src/main/java/com/finnect/user/application/port/in/SignupUseCase.java
  src/main/java/com/finnect/user/application/port/in/command/SignoutCommand.java
  src/main/java/com/finnect/user/application/port/in/error/EmailCodeNotVerifiedException.java
  src/main/java/com/finnect/user/application/port/in/error/UserDuplicateException.java
  src/main/java/com/finnect/user/application/port/in/exception/EmailCodeNotVerifiedException.java
  src/main/java/com/finnect/user/application/port/in/exception/UserDuplicateException.java
  src/main/java/com/finnect/user/application/port/out/DeleteRefreshTokenPort.java
  src/main/java/com/finnect/user/application/port/out/LoadEmailCodePort.java
  src/main/java/com/finnect/user/application/port/out/LoadRefreshTokenPort.java
  src/main/java/com/finnect/user/application/port/out/LoadUserPort.java
  src/main/java/com/finnect/user/application/port/out/SaveEmailCodePort.java
  src/main/java/com/finnect/user/application/port/out/error/EmailCodeNotFoundException.java
  src/main/java/com/finnect/user/application/port/out/error/RefreshTokenNotFoundException.java
  src/main/java/com/finnect/user/application/port/out/error/UserNotFoundException.java
  src/main/java/com/finnect/user/application/port/out/exception/EmailCodeNotFoundException.java
  src/main/java/com/finnect/user/application/port/out/exception/RefreshTokenNotFoundException.java
  src/main/java/com/finnect/user/application/service/FindUsernameService.java
  src/main/java/com/finnect/user/application/service/ResetPasswordService.java
  src/main/java/com/finnect/user/application/service/SignoutService.java
  src/main/java/com/finnect/user/application/service/SignupService.java
  src/main/java/com/finnect/user/application/service/UserDetailsServiceImpl.java
Labels: ✨ Feature, 📬 API

#154 fix: Refresh Token 쿠키 HttpOnly 설정 변경
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationFilter.java
Labels: 📬 API, Hotfix

#155 Refactor/153 add company name
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/FindAllPeopleResponse.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/PersonWithCompanyDto.java
  src/main/java/com/finnect/crm/application/port/in/person/FindPeopleUsecase.java
  src/main/java/com/finnect/crm/application/service/person/FindPersonService.java
  src/main/java/com/finnect/crm/domain/person/PersonWithCompany.java
  src/main/java/com/finnect/crm/domain/person/PersonWithCompanyState.java
Labels: 🔨 Refactor, 📬 API

#158 Feat/152 create default columns
  src/main/java/com/finnect/crm/adapter/out/persistence/column/ColumnPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/application/port/in/column/CreateNewColumnUseCase.java
  src/main/java/com/finnect/crm/application/port/out/column/SaveDataColumnPort.java
  src/main/java/com/finnect/crm/application/service/column/CreateNewColumnService.java
Labels: ✨ Feature

#159 Hotfix/157 json reissue
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationFilter.java
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/in/web/request/Reissue2Request.java
  src/main/java/com/finnect/user/adapter/in/web/request/Reissue2WorkspaceRequest.java
Labels: 📬 API, Hotfix

#160 Feat/152 create default columns
  src/main/java/com/finnect/crm/application/service/column/CreateNewColumnService.java
  src/main/java/com/finnect/workspace/application/CreateWorkspaceService.java
Labels: 🔨 Refactor

#164 Fix/163 create company bugfix
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyEntity.java
  src/main/java/com/finnect/crm/application/service/company/CreateCompanyService.java
  src/main/java/com/finnect/crm/domain/company/CompanyWithoutId.java
Labels: 🐞 BugFix

#168 feat: HTTP to HTTPS 리다이렉트 추가
  src/main/java/com/finnect/config/HttpsConfig.java
Labels: 🌏 Deploy

#169 Feat/166 default view
  src/main/java/com/finnect/crm/adapter/in/web/controller/deal/DealController.java
  src/main/java/com/finnect/crm/application/service/column/CreateNewColumnService.java
  src/main/java/com/finnect/view/adapter/in/web/req/CreateViewRequest.java
  src/main/java/com/finnect/view/adapter/out/ViewAdapter.java
  src/main/java/com/finnect/view/adapter/out/ViewRepository.java
  src/main/java/com/finnect/view/adapter/out/persistence/ViewEntity.java
  src/main/java/com/finnect/view/application/port/in/CreateViewUseCase.java
  src/main/java/com/finnect/view/application/port/in/ModifyViewUseCase.java
  src/main/java/com/finnect/view/application/port/out/LoadViewPort.java
  src/main/java/com/finnect/view/application/port/out/SaveViewPort.java
  src/main/java/com/finnect/view/application/service/CreateViewService.java
  src/main/java/com/finnect/view/application/service/ModifyViewService.java
  src/main/java/com/finnect/view/domain/View.java
  src/main/java/com/finnect/view/domain/state/ViewState.java
  src/main/java/com/finnect/workspace/application/CreateWorkspaceService.java
Labels: ✨ Feature

#170 fix: import문 수정
  src/main/java/com/finnect/crm/application/service/column/CreateNewColumnService.java
Labels: 🐞 BugFix

#176 Feat/165 get company
  .gitignore
  src/main/java/com/finnect/crm/adapter/in/web/controller/company/CompanyController.java
  src/main/java/com/finnect/crm/adapter/in/web/res/company/CellDto.java
  src/main/java/com/finnect/crm/adapter/in/web/res/company/GetCompanyResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/column/ColumnPersistenceLoadAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/column/DataColumnEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/column/DataColumnRepository.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyPersistenceAdapter.java
  src/main/java/com/finnect/crm/application/port/in/company/LoadCompanyUseCase.java
  src/main/java/com/finnect/crm/application/port/out/column/LoadDataColumnPort.java
  src/main/java/com/finnect/crm/application/service/company/LoadCompanyService.java
  src/main/java/com/finnect/crm/domain/company/CompanyDetail.java
Labels: ✨ Feature, 📬 API

#175 Feat/166 default view
  src/main/java/com/finnect/view/adapter/out/persistence/ViewEntity.java
  src/main/java/com/finnect/view/application/service/ModifyViewService.java
  src/main/java/com/finnect/view/domain/View.java
Labels: 📬 API

#177 Style/138 email html
  build.gradle
  src/main/java/com/finnect/workspace/application/InviteMembersService.java
  src/main/resources/templates/email.html
Labels: 🔨 Refactor, 🎨 Html&css

#174 Feat/43 check signup
  src/main/java/com/finnect/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/finnect/user/adapter/out/persistence/entity/UserRepository.java
  src/main/java/com/finnect/user/application/port/in/CheckDefaultWorkspaceQuery.java
  src/main/java/com/finnect/user/application/port/in/CheckSignupQuery.java
  src/main/java/com/finnect/user/application/port/in/command/CheckSignupsCommand.java
  src/main/java/com/finnect/user/application/port/out/ExistsUserPort.java
  src/main/java/com/finnect/user/application/service/UserInfoService.java
  src/main/java/com/finnect/workspace/application/CreateWorkspaceService.java
  src/test/java/com/finnect/workspace/application/CreateWorkspaceServiceTest.java
Labels: ✨ Feature

#182 Fix/75 check fk
  src/main/java/com/finnect/common/error/CustomException.java
  src/main/java/com/finnect/common/error/CustomExceptionHandler.java
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyPersistenceAdapter.java
  src/main/java/com/finnect/crm/application/port/out/company/CheckCompanyQuery.java
  src/main/java/com/finnect/crm/application/service/company/CreateCompanyService.java
  src/main/java/com/finnect/crm/application/service/person/CreatePersonService.java
  src/main/java/com/finnect/workspace/adaptor/in/web/MemberController.java
  src/main/java/com/finnect/workspace/adaptor/in/web/WorkspaceController.java
  src/main/java/com/finnect/workspace/adaptor/out/persistence/WorkspacePersistenceAdapter.java
  src/main/java/com/finnect/workspace/application/CheckAuthorityService.java
  src/main/java/com/finnect/workspace/application/CreateWorkspaceService.java
  src/main/java/com/finnect/workspace/application/FindMembersService.java
  src/main/java/com/finnect/workspace/application/GetWorkspaceService.java
  src/main/java/com/finnect/workspace/application/InviteMembersService.java
  src/main/java/com/finnect/workspace/application/MemberInfoService.java
  src/main/java/com/finnect/workspace/application/RenameWorkspaceService.java
  src/main/java/com/finnect/workspace/application/port/in/GetWorkspaceQuery.java
  src/main/java/com/finnect/workspace/application/port/out/CheckWorkspaceQuery.java
  src/main/java/com/finnect/workspace/application/port/out/GetWorkspacesPort.java
Labels: 🐞 BugFix, 🔨 Refactor

#185 fix: 초대 시 초대한 사람과 초대할 워크스페이스를 받고, 메일 전송 로직을 도메인 모델로 이동
  src/main/java/com/finnect/workspace/adaptor/in/web/WorkspaceController.java
  src/main/java/com/finnect/workspace/adaptor/in/web/res/dto/InvitationDto.java
  src/main/java/com/finnect/workspace/application/InviteMembersService.java
  src/main/java/com/finnect/workspace/application/port/in/InviteMembersCommand.java
  src/main/java/com/finnect/workspace/domain/Invitation.java
  src/main/java/com/finnect/workspace/domain/state/InvitationState.java
Labels: 🔨 Refactor

#186 Refactor/181 invite member
  src/main/java/com/finnect/workspace/application/InviteMembersService.java
  src/main/java/com/finnect/workspace/domain/Invitation.java
Labels: 🔨 Refactor

#187 refactor: redirection url 수정
  src/main/java/com/finnect/workspace/application/InviteMembersService.java
  src/main/java/com/finnect/workspace/domain/Invitation.java
Labels: 🔨 Refactor

#190 feat: 로그인 시 이름도 반환
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationFilter.java
  src/main/java/com/finnect/user/adapter/in/security/response/SigninResponse.java
  src/main/java/com/finnect/user/config/SecurityConfig.java
Labels: ✨ Feature, 📬 API

#192 refactor: 사용자 초대시 결과 이넘으로 반환
  src/main/java/com/finnect/workspace/adaptor/in/web/res/dto/InvitationDto.java
  src/main/java/com/finnect/workspace/application/InviteMembersService.java
  src/main/java/com/finnect/workspace/domain/Invitation.java
  src/main/java/com/finnect/workspace/domain/InvitationResult.java
  src/main/java/com/finnect/workspace/domain/state/InvitationState.java
Labels: 🔨 Refactor

#193 fix: 회원가입 시 비밀번호에 '*', '!' 허용
  src/main/java/com/finnect/user/application/port/in/command/SignupCommand.java
Labels: 🐞 BugFix, Hotfix

#191 Feat/30 view api
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyCellPersistenceAdapter.java
  src/main/java/com/finnect/crm/application/port/out/company/LoadCompanyWithCellPort.java
  src/main/java/com/finnect/crm/application/service/company/LoadCompanyWithCellUseService.java
  src/main/java/com/finnect/view/adapter/in/web/controller/ViewController.java
  src/main/java/com/finnect/view/adapter/in/web/req/PatchViewRequest.java
  src/main/java/com/finnect/view/adapter/in/web/res/CompanyViewInfoResponse.java
  src/main/java/com/finnect/view/adapter/in/web/res/DealViewInfoResponse.java
  src/main/java/com/finnect/view/application/port/in/ModifyViewUseCase.java
  src/main/java/com/finnect/view/application/service/ModifyViewService.java
  src/main/java/com/finnect/view/domain/View.java
  src/main/java/com/finnect/view/domain/ViewDetail.java
Labels: 🐞 BugFix

#195 feat: 쿠키를 사용하지 않는 로그아웃 API 추가
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/in/web/request/Signout2Request.java
Labels: 📬 API, Hotfix

#197 Fix/180 get company
  src/main/java/com/finnect/crm/application/service/company/LoadCompanyService.java
  src/main/java/com/finnect/crm/domain/cell/DataCell.java
Labels: 🐞 BugFix

#199 Feat/30 view api
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyCellPersistenceAdapter.java
  src/main/java/com/finnect/crm/application/service/company/LoadCompanyWithCellUseService.java
  src/main/java/com/finnect/crm/application/service/deal/LoadDealWithCellService.java
  src/main/java/com/finnect/crm/domain/cell/DataCell.java
Labels: ✨ Feature

#200 Fix/198 check domain
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyPersistenceAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyRepository.java
  src/main/java/com/finnect/crm/application/port/out/company/CheckCompanyQuery.java
  src/main/java/com/finnect/crm/application/service/company/CreateCompanyService.java
Labels: 🐞 BugFix

#201 Feat/196 create view
  src/main/java/com/finnect/crm/application/port/in/column/LoadDataColumnUseCase.java
  src/main/java/com/finnect/crm/application/service/column/LoadDataColumnService.java
  src/main/java/com/finnect/view/application/service/CreateViewService.java
Labels: ✨ Feature

#203 Feat/2 deal api
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/CellPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/DataRowRepository.java
Labels: ✨ Feature

#207 fix: PasswordConfig로 PasswordEncoder 분리
  src/main/java/com/finnect/user/config/PasswordConfig.java
  src/main/java/com/finnect/user/config/SecurityConfig.java
Labels: 🐞 BugFix, Hotfix

#209 refactor: MultiSelect 주석 처리
  src/main/java/com/finnect/crm/domain/column/ColumnType.java
Labels: 🔨 Refactor

#210 Feat/2 deal api
  build.gradle
  src/main/java/com/finnect/config/QueryDSLConfig.java
  src/main/java/com/finnect/crm/adapter/in/web/controller/deal/DealController.java
  src/main/java/com/finnect/crm/adapter/in/web/res/deal/DealDetailResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/deal/DealCellDSLPersistenceAdapter.java
  src/main/java/com/finnect/crm/application/port/in/deal/LoadDealWithCellUseCase.java
  src/main/java/com/finnect/crm/application/port/out/deal/LoadDealWithCellDSLPort.java
  src/main/java/com/finnect/crm/application/service/deal/LoadDealWithCellService.java
  src/main/java/com/finnect/crm/domain/deal/DealCellDetail.java
Labels: ✨ Feature

#212 Refactor/211 create view
  src/main/java/com/finnect/view/adapter/in/web/controller/DealViewController.java
  src/main/java/com/finnect/view/adapter/in/web/controller/ViewController.java
  src/main/java/com/finnect/view/adapter/in/web/req/CreateViewRequest.java
Labels: 🔨 Refactor

#214 Feat/213 fix deal detail
  src/main/java/com/finnect/crm/application/service/deal/LoadDealWithCellService.java
  src/main/java/com/finnect/note/adapter/in/web/NoteController.java
Labels: 🐞 BugFix

#216 Refactor/215 smtp
  src/main/java/com/finnect/user/application/service/SendEmailCodeService.java
  src/main/java/com/finnect/workspace/domain/Invitation.java
  src/main/resources/templates/emailCode.html
  src/main/resources/templates/invitation.html
Labels: 🙋‍♂️ Question, 🎨 Html&css

#219 Docs/218 api
  src/main/java/com/finnect/crm/adapter/in/web/controller/company/CompanyController.java
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/workspace/adaptor/in/web/MemberController.java
  src/main/java/com/finnect/workspace/adaptor/in/web/WorkspaceController.java
Labels: 📃 Docs, 📬 API
