Repository KNU-Finnect/finnect_backend, pull requests merged in 2024-05, with the labels that each got.

#34 Feat/1 jwt auth
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/finnect/common/SelfValidating.java
  src/main/java/com/finnect/user/adapter/in/security/AccessDeniedHandlerImpl.java
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationEntryPointImpl.java
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationFilter.java
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationProviderImpl.java
  src/main/java/com/finnect/user/adapter/in/security/AuthorizationFilter.java
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/in/web/request/SignupRequest.java
  src/main/java/com/finnect/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/finnect/user/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/finnect/user/adapter/out/persistence/entity/UserRepository.java
  src/main/java/com/finnect/user/application/jwt/JwtProvider.java
  src/main/java/com/finnect/user/application/port/in/ReissueUseCase.java
  src/main/java/com/finnect/user/application/port/in/SignupUseCase.java
  src/main/java/com/finnect/user/application/port/in/command/ReissueCommand.java
  src/main/java/com/finnect/user/application/port/in/command/SignupCommand.java
  src/main/java/com/finnect/user/application/port/out/CreateUserPort.java
  src/main/java/com/finnect/user/application/port/out/GetUserPort.java
  src/main/java/com/finnect/user/application/service/AuthenticationService.java
  src/main/java/com/finnect/user/application/service/UserService.java
  src/main/java/com/finnect/user/config/SecurityConfig.java
  src/main/java/com/finnect/user/domain/User.java
  src/main/java/com/finnect/user/domain/UserDetailsImpl.java
  src/main/java/com/finnect/user/domain/UserInfo.java
  src/main/java/com/finnect/user/exception/InvalidRefreshTokenException.java
  src/main/java/com/finnect/user/exception/UserNotFoundException.java
  src/main/java/com/finnect/user/state/UserInfoState.java
  src/main/java/com/finnect/user/state/UserState.java
  src/main/java/com/finnect/user/vo/AccessToken.java
  src/main/java/com/finnect/user/vo/JwtPair.java
  src/main/java/com/finnect/user/vo/UserId.java
  src/main/java/com/finnect/user/vo/WorkspaceAuthority.java
  src/main/java/com/finnect/user/vo/WorkspaceId.java
  src/main/resources/application.properties
  src/test/java/com/finnect/user/application/jwt/JwtProviderTests.java
  src/test/java/com/finnect/user/application/port/in/command/SignupCommandTests.java
  src/test/resources/application.properties
Labels: ✨ Feature

#50 Feat/36 change password
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/in/web/request/ChangePasswordRequest.java
  src/main/java/com/finnect/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/finnect/user/application/port/in/ChangePasswordUseCase.java
  src/main/java/com/finnect/user/application/port/in/command/ChangePasswordCommand.java
  src/main/java/com/finnect/user/application/port/out/LoadUserPort.java
  src/main/java/com/finnect/user/application/port/out/UpdateUserPort.java
  src/main/java/com/finnect/user/application/service/AccountService.java
  src/main/java/com/finnect/user/application/service/AuthenticationService.java
  src/main/java/com/finnect/user/domain/User.java
  src/main/java/com/finnect/user/vo/UserId.java
  src/test/java/com/finnect/user/application/port/in/command/ChangePasswordCommandTests.java
Labels: ✨ Feature

#51 Refact/48 relation mapping
  src/main/java/com/finnect/crm/adapter/in/web/controller/deal/DealController.java
  src/main/java/com/finnect/crm/adapter/out/cell/CellPersistenceLoadAdapter.java
  src/main/java/com/finnect/crm/adapter/out/cell/CellPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/adapter/out/cell/DataCellRepository.java
  src/main/java/com/finnect/crm/adapter/out/cell/persistence/CellId.java
  src/main/java/com/finnect/crm/adapter/out/cell/persistence/DataCellEntity.java
  src/main/java/com/finnect/crm/adapter/out/column/ColumnPersistenceLoadAdapter.java
  src/main/java/com/finnect/crm/adapter/out/column/ColumnPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/adapter/out/column/DataColumnRepository.java
  src/main/java/com/finnect/crm/adapter/out/column/persistence/DataColumnEntity.java
  src/main/java/com/finnect/crm/application/port/out/column/LoadDataColumnPort.java
  src/main/java/com/finnect/crm/application/port/out/column/SaveDataColumnPort.java
  src/main/java/com/finnect/crm/application/service/cell/CreateNewColumnService.java
  src/main/java/com/finnect/crm/application/service/cell/LoadDataColumnService.java
  src/main/java/com/finnect/crm/domain/cell/DataCell.java
Labels: 🔨 Refactor

#63 Feat/37 redis auth
  build.gradle
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationFilter.java
  src/main/java/com/finnect/user/adapter/in/security/AuthenticationProviderImpl.java
  src/main/java/com/finnect/user/adapter/in/security/AuthorizationFilter.java
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/out/cache/RefreshTokenCacheAdapter.java
  src/main/java/com/finnect/user/adapter/out/cache/entity/RefreshTokenEntity.java
  src/main/java/com/finnect/user/adapter/out/cache/entity/RefreshTokenRepository.java
  src/main/java/com/finnect/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/finnect/user/application/jwt/JwtProvider.java
  src/main/java/com/finnect/user/application/port/in/AuthenticateUseCase.java
  src/main/java/com/finnect/user/application/port/in/AuthorizeUseCase.java
  src/main/java/com/finnect/user/application/port/in/IssueUseCase.java
  src/main/java/com/finnect/user/application/port/in/ReissueUseCase.java
  src/main/java/com/finnect/user/application/port/in/UserDetailsQuery.java
  src/main/java/com/finnect/user/application/port/in/command/AuthenticateCommand.java
  src/main/java/com/finnect/user/application/port/in/command/AuthorizeCommand.java
  src/main/java/com/finnect/user/application/port/in/command/IssueCommand.java
  src/main/java/com/finnect/user/application/port/out/LoadRefreshTokenPort.java
  src/main/java/com/finnect/user/application/port/out/LoadUserPort.java
  src/main/java/com/finnect/user/application/port/out/SaveRefreshTokenPort.java
  src/main/java/com/finnect/user/application/port/out/exception/RefreshTokenNotFoundException.java
  src/main/java/com/finnect/user/application/port/out/exception/UserNotFoundException.java
  src/main/java/com/finnect/user/application/service/AuthenticationService.java
  src/main/java/com/finnect/user/application/service/TokenService.java
  src/main/java/com/finnect/user/application/service/UserDetailsServiceImpl.java
  src/main/java/com/finnect/user/config/RedisConfig.java
  src/main/java/com/finnect/user/config/SecurityConfig.java
  src/main/java/com/finnect/user/domain/AccessToken.java
  src/main/java/com/finnect/user/domain/RefreshToken.java
  src/main/java/com/finnect/user/domain/TokenPair.java
  src/main/java/com/finnect/user/domain/User.java
  src/main/java/com/finnect/user/domain/UserDetailsImpl.java
  src/main/java/com/finnect/user/domain/UserInfo.java
  src/main/java/com/finnect/user/exception/InvalidRefreshTokenException.java
  src/main/java/com/finnect/user/state/AccessTokenState.java
  src/main/java/com/finnect/user/state/RefreshTokenState.java
  src/main/java/com/finnect/user/state/TokenPairState.java
  src/main/java/com/finnect/user/vo/AccessToken.java
  src/main/java/com/finnect/user/vo/JwtPair.java
  src/main/java/com/finnect/user/vo/UserId.java
  src/main/java/com/finnect/user/vo/WorkspaceId.java
  src/test/java/com/finnect/user/application/jwt/JwtProviderTests.java
  src/test/java/com/finnect/user/application/port/in/command/ChangePasswordCommandTests.java
Labels: ✨ Feature

#64 build: docker 파일 삭제
  docker-compose.yml
Labels: 🌏 Deploy

#69 Feat/57 create company
  src/main/java/com/finnect/crm/adapter/in/web/controller/company/CompanyController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/company/CreateCompanyRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/res/company/CompanyDto.java
  src/main/java/com/finnect/crm/adapter/in/web/res/company/CreateCompanyResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyPersistenceAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyRepository.java
  src/main/java/com/finnect/crm/application/port/in/company/CreateCompanyCommand.java
  src/main/java/com/finnect/crm/application/port/in/company/CreateCompanyUsecase.java
  src/main/java/com/finnect/crm/application/port/out/company/LoadCompanyPort.java
  src/main/java/com/finnect/crm/application/port/out/company/SaveCompanyPort.java
  src/main/java/com/finnect/crm/application/port/out/company/SearchCompanyPort.java
  src/main/java/com/finnect/crm/application/service/company/CreateCompanyService.java
  src/main/java/com/finnect/crm/domain/company/CompanyWithoutId.java
Labels: ✨ Feature, 📬 API

#71 Feat/58 create company column
  src/main/java/com/finnect/crm/adapter/in/web/controller/cell/DealCellController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/cell/CreateCompanyColumnRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/res/cell/CreateCompanyColumnResponse.java
  src/main/java/com/finnect/crm/domain/cell/DataColumn.java
Labels: ✨ Feature, 📬 API

#73 Feat/56 company api
  src/main/java/com/finnect/crm/adapter/in/web/controller/cell/DealCellController.java
  src/main/java/com/finnect/crm/adapter/in/web/controller/company/CompanyController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/cell/CreateCompanyColumnRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/req/company/CreateCompanyRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/res/cell/CreateCompanyColumnResponse.java
  src/main/java/com/finnect/crm/adapter/in/web/res/company/CompanyDto.java
  src/main/java/com/finnect/crm/adapter/in/web/res/company/CreateCompanyResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyPersistenceAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/CompanyRepository.java
  src/main/java/com/finnect/crm/adapter/out/persistence/company/PeopleEntity.java
  src/main/java/com/finnect/crm/application/port/in/company/CreateCompanyCommand.java
  src/main/java/com/finnect/crm/application/port/in/company/CreateCompanyUsecase.java
  src/main/java/com/finnect/crm/application/port/out/company/LoadCompanyPort.java
  src/main/java/com/finnect/crm/application/port/out/company/SaveCompanyPort.java
  src/main/java/com/finnect/crm/application/port/out/company/SearchCompanyPort.java
  src/main/java/com/finnect/crm/application/service/company/CreateCompanyService.java
  src/main/java/com/finnect/crm/domain/cell/DataColumn.java
  src/main/java/com/finnect/crm/domain/company/Company.java
  src/main/java/com/finnect/crm/domain/company/CompanyState.java
  src/main/java/com/finnect/crm/domain/company/CompanyWithoutId.java
Labels: ✨ Feature, 📬 API

#74 Feat/59 create person
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/person/CreatePersonRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/CreatePersonResponse.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/PersonDto.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonPersistenceAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonRepository.java
  src/main/java/com/finnect/crm/application/port/in/person/CreatePersonCommand.java
  src/main/java/com/finnect/crm/application/port/in/person/CreatePersonUsecase.java
  src/main/java/com/finnect/crm/application/port/out/person/SavePersonPort.java
  src/main/java/com/finnect/crm/application/service/person/CreatePersonService.java
  src/main/java/com/finnect/crm/domain/person/Person.java
  src/main/java/com/finnect/crm/domain/person/PersonWithoutId.java
Labels: ✨ Feature, 📬 API

#76 Feat/61 update person
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/person/UpdatePersonRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/UpdatePersonResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonPersistenceAdapter.java
  src/main/java/com/finnect/crm/application/port/in/person/UpdatePersonCommand.java
  src/main/java/com/finnect/crm/application/port/in/person/UpdatePersonUsecase.java
  src/main/java/com/finnect/crm/application/port/out/person/LoadPersonPort.java
  src/main/java/com/finnect/crm/application/service/person/UpdatePersonService.java
  src/main/java/com/finnect/crm/domain/person/Person.java
Labels: ✨ Feature, 📬 API

#77 Feat/60 search people
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/FindPeopleResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonPersistenceAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonRepository.java
  src/main/java/com/finnect/crm/application/port/in/person/FindPeopleUsecase.java
  src/main/java/com/finnect/crm/application/port/out/person/LoadPeoplePort.java
  src/main/java/com/finnect/crm/application/service/person/FindPersonService.java
Labels: ✨ Feature, 📬 API

#78 Feat/62 delete person
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonPersistenceAdapter.java
  src/main/java/com/finnect/crm/application/port/in/person/DeletePersonUsecase.java
  src/main/java/com/finnect/crm/application/port/out/person/DeletePersonPort.java
  src/main/java/com/finnect/crm/application/service/person/DeletePersonService.java
Labels: ✨ Feature, 📬 API

#79 Feat/72 people api
  src/main/java/com/finnect/crm/adapter/in/web/controller/person/PersonController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/person/CreatePersonRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/req/person/UpdatePersonRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/CreatePersonResponse.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/FindPeopleResponse.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/PersonDto.java
  src/main/java/com/finnect/crm/adapter/in/web/res/person/UpdatePersonResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonPersistenceAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/person/PersonRepository.java
  src/main/java/com/finnect/crm/application/port/in/person/CreatePersonCommand.java
  src/main/java/com/finnect/crm/application/port/in/person/CreatePersonUsecase.java
  src/main/java/com/finnect/crm/application/port/in/person/DeletePersonUsecase.java
  src/main/java/com/finnect/crm/application/port/in/person/FindPeopleUsecase.java
  src/main/java/com/finnect/crm/application/port/in/person/UpdatePersonCommand.java
  src/main/java/com/finnect/crm/application/port/in/person/UpdatePersonUsecase.java
  src/main/java/com/finnect/crm/application/port/out/person/DeletePersonPort.java
  src/main/java/com/finnect/crm/application/port/out/person/LoadPeoplePort.java
  src/main/java/com/finnect/crm/application/port/out/person/LoadPersonPort.java
  src/main/java/com/finnect/crm/application/port/out/person/SavePersonPort.java
  src/main/java/com/finnect/crm/application/service/person/CreatePersonService.java
  src/main/java/com/finnect/crm/application/service/person/DeletePersonService.java
  src/main/java/com/finnect/crm/application/service/person/FindPersonService.java
  src/main/java/com/finnect/crm/application/service/person/UpdatePersonService.java
  src/main/java/com/finnect/crm/domain/person/Person.java
  src/main/java/com/finnect/crm/domain/person/PersonState.java
  src/main/java/com/finnect/crm/domain/person/PersonWithoutId.java
Labels: ✨ Feature, 📬 API

#85 Feat/82 check deal logs api
  src/main/java/com/finnect/crm/adapter/in/web/controller/dealLog/DealLogController.java
  src/main/java/com/finnect/crm/adapter/in/web/res/dealLog/DealLogResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/dealLog/DealLogAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/dealLog/DealLogRepository.java
  src/main/java/com/finnect/crm/application/port/in/dealLog/LoadDealLogUseCase.java
  src/main/java/com/finnect/crm/application/port/out/dealLog/LoadDealLogPort.java
  src/main/java/com/finnect/crm/application/service/dealLog/LoadDealLogService.java
Labels: 📬 API

#86 Feat/2 deal api
  src/main/java/com/finnect/crm/adapter/in/web/controller/dealLog/DealLogController.java
  src/main/java/com/finnect/crm/adapter/in/web/res/dealLog/DealLogResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/dealLog/DealLogAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/dealLog/DealLogEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/dealLog/DealLogRepository.java
  src/main/java/com/finnect/crm/application/port/in/dealLog/CreateDealLogUseCase.java
  src/main/java/com/finnect/crm/application/port/in/dealLog/LoadDealLogUseCase.java
  src/main/java/com/finnect/crm/application/port/out/dealLog/LoadDealLogPort.java
  src/main/java/com/finnect/crm/application/port/out/dealLog/SaveDealLogPort.java
  src/main/java/com/finnect/crm/application/service/deal/CreateDealService.java
  src/main/java/com/finnect/crm/application/service/dealLog/CreateDealLogService.java
  src/main/java/com/finnect/crm/application/service/dealLog/LoadDealLogService.java
  src/main/java/com/finnect/crm/domain/dealLog/DealLog.java
  src/main/java/com/finnect/crm/domain/dealLog/state/DealLogState.java
Labels: 📬 API

#87 feat: 프론트엔드에 CORS 허용
  src/main/java/com/finnect/user/config/SecurityConfig.java
Labels: 🌏 Deploy

#89 fix: CORS 허용을 주소에서 패턴으로 변경
  src/main/java/com/finnect/user/config/SecurityConfig.java
Labels: 🌏 Deploy

#93 Feat/92 modify deal attribute api
  src/main/java/com/finnect/crm/adapter/in/web/controller/cell/DealCellController.java
  src/main/java/com/finnect/crm/adapter/in/web/controller/column/ColumnController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/column/ModifyColumnRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/res/cell/DealColumnResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/CellPersistenceLoadAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/CellPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/DataCellEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/DataCellRepository.java
  src/main/java/com/finnect/crm/adapter/out/persistence/column/ColumnPersistenceLoadAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/column/ColumnPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/application/port/in/cell/ResetDataCellUseCase.java
  src/main/java/com/finnect/crm/application/port/in/column/ModifyColumnUseCase.java
  src/main/java/com/finnect/crm/application/port/out/cell/LoadDataCellPort.java
  src/main/java/com/finnect/crm/application/port/out/cell/SaveCellPort.java
  src/main/java/com/finnect/crm/application/port/out/column/LoadDataColumnPort.java
  src/main/java/com/finnect/crm/application/port/out/column/SaveDataColumnPort.java
  src/main/java/com/finnect/crm/application/service/cell/CreateNewColumnService.java
  src/main/java/com/finnect/crm/application/service/cell/ResetDataColumnService.java
  src/main/java/com/finnect/crm/application/service/column/ModifyColumnService.java
  src/main/java/com/finnect/crm/domain/cell/DataCell.java
  src/main/java/com/finnect/crm/domain/cell/DataColumn.java
  src/main/java/com/finnect/user/config/SecurityConfig.java
Labels: 📬 API

#94 Column 정보 변경 API
  src/main/java/com/finnect/crm/adapter/in/web/controller/cell/DealCellController.java
  src/main/java/com/finnect/crm/adapter/in/web/controller/column/ColumnController.java
  src/main/java/com/finnect/crm/adapter/in/web/req/column/ModifyColumnRequest.java
  src/main/java/com/finnect/crm/adapter/in/web/res/cell/DealColumnResponse.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/CellPersistenceLoadAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/CellPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/DataCellEntity.java
  src/main/java/com/finnect/crm/adapter/out/persistence/cell/DataCellRepository.java
  src/main/java/com/finnect/crm/adapter/out/persistence/column/ColumnPersistenceLoadAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/column/ColumnPersistenceSaveAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/deal/DealCellPersistenceAdapter.java
  src/main/java/com/finnect/crm/adapter/out/persistence/deal/DealPersistenceAdapter.java
  src/main/java/com/finnect/crm/application/port/in/cell/ResetDataCellUseCase.java
  src/main/java/com/finnect/crm/application/port/in/column/ModifyColumnUseCase.java
  src/main/java/com/finnect/crm/application/port/out/cell/LoadDataCellPort.java
  src/main/java/com/finnect/crm/application/port/out/cell/SaveCellPort.java
  src/main/java/com/finnect/crm/application/port/out/column/LoadDataColumnPort.java
  src/main/java/com/finnect/crm/application/port/out/column/SaveDataColumnPort.java
  src/main/java/com/finnect/crm/application/service/cell/CreateNewColumnService.java
  src/main/java/com/finnect/crm/application/service/cell/ResetDataColumnService.java
  src/main/java/com/finnect/crm/application/service/column/ModifyColumnService.java
  src/main/java/com/finnect/crm/domain/cell/DataCell.java
  src/main/java/com/finnect/crm/domain/cell/DataColumn.java
Labels: 📬 API

#88 Feat/38 email auth
  build.gradle
  src/main/java/com/finnect/common/ApiUtils.java
  src/main/java/com/finnect/user/adapter/in/web/UserController.java
  src/main/java/com/finnect/user/adapter/in/web/request/EmailAuthPostRequest.java
  src/main/java/com/finnect/user/adapter/in/web/request/EmailAuthVerifyRequest.java
  src/main/java/com/finnect/user/adapter/in/web/request/PasswordRequest.java
  src/main/java/com/finnect/user/adapter/out/cache/EmailCodeCacheAdapter.java
  src/main/java/com/finnect/user/adapter/out/cache/entity/EmailCodeEntity.java
  src/main/java/com/finnect/user/adapter/out/cache/entity/EmailCodeRepository.java
  src/main/java/com/finnect/user/adapter/out/persistence/UserPersistenceAdapter.java
  src/main/java/com/finnect/user/adapter/out/persistence/entity/UserEntity.java
  src/main/java/com/finnect/user/adapter/out/persistence/entity/UserRepository.java
  src/main/java/com/finnect/user/application/password/PasswordGenerator.java
  src/main/java/com/finnect/user/application/port/in/FindUsernameUseCase.java
  src/main/java/com/finnect/user/application/port/in/ResetPasswordUseCase.java
  src/main/java/com/finnect/user/application/port/in/SendEmailCodeUseCase.java
  src/main/java/com/finnect/user/application/port/in/SignupUseCase.java
  src/main/java/com/finnect/user/application/port/in/VerifyEmailCodeUseCase.java
  src/main/java/com/finnect/user/application/port/in/command/FindUsernameCommand.java
  src/main/java/com/finnect/user/application/port/in/command/ResetPasswordCommand.java
  src/main/java/com/finnect/user/application/port/in/command/SendEmailCodeCommand.java
  src/main/java/com/finnect/user/application/port/in/command/VerifyEmailCodeCommand.java
  src/main/java/com/finnect/user/application/port/in/exception/EmailCodeNotVerifiedException.java
  src/main/java/com/finnect/user/application/port/out/LoadEmailCodePort.java
  src/main/java/com/finnect/user/application/port/out/LoadUserPort.java
  src/main/java/com/finnect/user/application/port/out/SaveEmailCodePort.java
  src/main/java/com/finnect/user/application/port/out/exception/EmailCodeNotFoundException.java
  src/main/java/com/finnect/user/application/port/out/exception/UserNotFoundException.java
  src/main/java/com/finnect/user/application/service/FindUsernameService.java
  src/main/java/com/finnect/user/application/service/ResetPasswordService.java
  src/main/java/com/finnect/user/application/service/SendEmailCodeService.java
  src/main/java/com/finnect/user/application/service/SignupService.java
  src/main/java/com/finnect/user/application/service/TokenService.java
  src/main/java/com/finnect/user/application/service/UserDetailsServiceImpl.java
  src/main/java/com/finnect/user/application/service/UserInfoService.java
  src/main/java/com/finnect/user/domain/EmailCode.java
  src/main/java/com/finnect/user/state/EmailCodeState.java
  src/test/java/com/finnect/user/application/password/PasswordGeneratorTests.java
  src/test/java/com/finnect/user/application/port/in/command/FindUsernameCommandTests.java
  src/test/java/com/finnect/user/application/port/in/command/ResetPasswordCommandTests.java
  src/test/java/com/finnect/user/application/port/in/command/SendEmailCodeCommandTests.java
  src/test/java/com/finnect/user/application/port/in/command/SignupCommandTests.java
Labels: ✨ Feature
